apiVersion: bliblablub/alphav1
kind: RandomKind
metadata:
  name: kubernetes-so-demo
  labels:
    app: demonstrate-envars
spec:
  workloads:
  - name: workload1
    relation:
      workload: workload2
    spec:
      template:
        metadata:
          labels:
            app: demonstrate-envars
            tier: web
        spec:
          containers:
          - name: hello-app-server
            image: ${{image_tag}}